[package]
name = "lean_rs"
version = "0.1.0"
authors = ["Gerardo Salazar <gsalaz9800@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
chrono = "0.4.6"
chrono-tz = "0.5"
serde = "1.0.99"